
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    volumes:
      - ./backend/db:/app/backend/db
      - ./backend/problems:/app/backend/problems
      - ./backend/public:/app/backend/public
      - ./backend/archive:/app/backend/archive
      - ./.env.secret:/app/.env.secret
    environment:
      - TZ=Asia/Shanghai

  frontend:
    build:
      context: frontend  # 构建上下文是 frontend 目录
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5050:80"  # 改为映射到宿主机 5050，避免和 1Panel 的 80 端口冲突
    depends_on:
      - backend
